### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by vigo** [gelistiriciyiz-biz/gelistiriciyiz.biz#1]
Selam @onur, eski repo çöp oldu, buradan devam edelim. En son "eğer ciddi ciddi yapacaksan seve seve açarım rust'ı" demiştim. Ben anlamadığım için post yazman çok zor. Diyorsan ki "ben ve hatta bazı rust sever arkadaşlarım olaya el atar" o zaman ne duruyoruz ?

**Comment by onur** [comment]
Merhaba.

Ciddi ciddi yapmayı düşünüyorum ama gelistiriciyiz.biz'in middleman kullanması biraz korkuttu. Hiç tecrübem olmayan bir platform ve yazıları yollamadan önce test etmek isterim. gelistiriciyiz.biz'i çalıştırmayı bir türlü başaramadım. `bundle install`'ın başarıyla tamamlanmasının ardından `rake` şu hatayı veriyor:

```
== The Middleman is loading
/tmp/git.gelistiriciyiz.biz/config.rb:4:in `require': cannot load such file -- ./creds (LoadError)
	from /tmp/git.gelistiriciyiz.biz/config.rb:4:in `initialize'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/extensions.rb:162:in `instance_eval'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/extensions.rb:162:in `initialize'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/data.rb:33:in `initialize'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/application.rb:188:in `initialize'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:52:in `new'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/core_extensions/request.rb:52:in `inst'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/preview_server.rb:103:in `new_app'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/preview_server.rb:21:in `start'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/cli/server.rb:78:in `server'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/cli.rb:72:in `method_missing'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/lib/middleman-core/cli.rb:20:in `start'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.10/bin/middleman:18:in `<top (required)>'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/bin/middleman:23:in `load'
	from /tmp/git.gelistiriciyiz.biz/vendor/bundle/ruby/2.2.0/bin/middleman:23:in `<main>'
```

Yazdığınız yazılara da baktığımda gelistiriciyiz.biz daha çok ipucu formatında hazırlanmış. Ben rust için daha kapsamlı yazılar yazmayı planlıyordum, uygun olur mu bilemiyorum.

**Comment by vigo** [comment]
`cannot load such file -- ./creds (LoadError)`

root'da `creds.rb` diye bir file lazım... içine fake olarak;

```rb
DEPLOY_USER = "kullanıcı_adı"
DEPLOY_HOST = "server"
DEPLOY_PATH = "/path/to/site"
```

koy... [şuralarda](https://github.com/gelistiriciyiz-biz/git.gelistiriciyiz.biz/blob/master/readme.md) hep yazmıştım ama buraya eklememişim :)

**Comment by vigo** [comment]
Keza diğer siteler gibi olacak "rust.gelistiriciyiz.biz"... git, bash, osx hatta golang'e bakabilirsin.

**Comment by onur** [comment]
Tamamdır, `creds.rb` sadece deployment için gerekli zannettim.

O zaman şöyle yapabiliriz. Ben önce bir kaç yazı hazırlamayı deniyeyim, sizin içinde uygunsa açarız.

**Comment by vigo** [comment]
ok, sen antreman yok. hazır olduğunda haber ver, ben "rust.gelistiriciyiz.biz" in reposunu vs yapayım, orada PR yaparsın ok?

**Comment by onur** [comment]
tamam en kısa zamanda bir şeyler hazırlayacağım
